-- Bootstrap targets for Hermes
-- Generated by reconstructing queryurls from parser.py and public site inspection.
-- Some JSON API targets are omitted/disabled because their private API endpoints
-- could not be reconstructed without network inspection.
--
-- /websites in the Telegram bot lists only rows in hermes.targets with enabled = true
-- (see bot.py). A long list on another deployment means that database had many targets;
-- after this bootstrap you will only see the agencies you INSERT here as enabled.
--
-- To apply against the repo's k8s/hermes/postgres.yaml (StatefulSet postgres, DB user hermes):
--   kubectl exec -i -n hermes statefulset/postgres -- \
--     psql -U hermes -d hermes < misc/targets_bootstrap.sql
--
-- Docker Compose: docker exec -i hermes-database psql -U hermes -d hermes < misc/targets_bootstrap.sql
--
-- Debug: list enabled targets from the scraper pod (needs image with WORKDIR /scraper/hermes):
--   kubectl exec -n hermes deploy/hermes-scraper -- \
--     python3 -c "import hermes_utils.db as db; print(db.fetch_all('SELECT agency, enabled FROM hermes.targets WHERE enabled'))"

-- ─── HTML scrapers ────────────────────────────────────────────────────────────
-- These load a full web page; the parser picks listings out of the HTML.

INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'pararius',
  'https://www.pararius.com/apartments/nederland/0-2500',
  'GET',
  '{"agency": "Pararius", "website": "https://www.pararius.com"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

-- At Home Vastgoed sits behind Cloudflare; use curl_cffi (CF_GET) with a
-- Chrome TLS fingerprint. Listings are not in the DOM but embedded as a
-- Vuex SET_PROPERTIES_COLLECTION JSON commit (see parse_athomevastgoed).
INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'athomevastgoed',
  'https://www.athomevastgoed.nl/en/rental-listing?ray=20&order=latest_desc',
  'CF_GET',
  '{"agency": "At Home Vastgoed", "website": "https://www.athomevastgoed.nl"}',
  '{}',
  '{"Accept-Language":"nl-NL,nl;q=0.9,en;q=0.8","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}',
  true
);

INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'vanderlinden',
  'https://www.vanderlinden.nl/woningen/huur/',
  'GET',
  '{"agency": "Van der Linden", "website": "https://www.vanderlinden.nl"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'wooove',
  'https://hurenbijwooove.nl/woningen-te-huur/',
  'GET',
  '{"agency": "Wooove", "website": "https://hurenbijwooove.nl"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'ikwilhuren',
  'https://ikwilhuren.nu/huurwoningen/',
  'GET',
  '{"agency": "IkWilHuren", "website": "https://ikwilhuren.nu"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'maxxhuren',
  'https://maxxhuren.nl/huurwoningen/',
  'GET',
  '{"agency": "MaxxHuren", "website": "https://maxxhuren.nl"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

-- WoonMatch Waterland: Next.js SSR page — listings in __NEXT_DATA__ JSON blob.
INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'woonmatchwaterland',
  'https://woonmatchwaterland.nl/houses',
  'GET',
  '{"agency": "WoonMatch Waterland", "website": "https://woonmatchwaterland.nl"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

-- VBO / Vastgoed Nederland: HTML with `a.propertyLink` cards.
INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'vbo',
  'https://aanbod.vastgoednederland.nl/huurwoningen',
  'GET',
  '{"agency": "Vastgoed Nederland (VBO)", "website": "https://aanbod.vastgoednederland.nl"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}',
  true
);

-- ─── JSON API scrapers ────────────────────────────────────────────────────────
-- Woonzeker: the parser source explicitly mentions the JSON endpoint URL.
INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
VALUES (
  'woonzeker',
  'https://woonzeker.com/api/ms/listing/properties?filter[import_type]=RentResident&per_page=100',
  'GET',
  '{"agency": "Woonzeker", "website": "https://woonzeker.com"}',
  '{}',
  '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36", "Accept": "application/json"}',
  true
);

-- ─── Targets that need manual API discovery ───────────────────────────────────
-- The following sources use private/undocumented JSON APIs.
-- To enable them, open the website in Chrome DevTools → Network tab → filter XHR/Fetch,
-- then refresh the page and find the API call that returns listings.
-- Copy the URL + headers + body here, then set enabled = true.

-- Vesteda: response must be JSON with {"results": {"objects": [...]}}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('vesteda', 'REPLACE_ME', 'GET',
--   '{"agency": "Vesteda", "website": "https://www.vesteda.com"}', '{}', '{}', false);

-- De Alliantie: response must be JSON with {"data": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('alliantie', 'REPLACE_ME', 'GET',
--   '{"agency": "De Alliantie", "website": "https://ik-zoek.de-alliantie.nl"}', '{}', '{}', false);

-- Funda: Elasticsearch NDJSON multi-search — method=POST_NDJSON, complex body
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('funda', 'REPLACE_ME', 'POST_NDJSON',
--   '{"agency": "Funda", "website": "https://funda.nl"}', '[]', '{}', false);

-- Rebo Groep: response must be JSON with {"hits": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('rebo', 'REPLACE_ME', 'GET',
--   '{"agency": "Rebo Groep", "website": "https://www.rebogroep.nl"}', '{}', '{}', false);

-- Ooms: response must be JSON with {"objects": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('ooms', 'REPLACE_ME', 'GET',
--   '{"agency": "Ooms", "website": "https://ooms.com"}', '{}', '{}', false);

-- Roofz: response must be JSON with {"data": [...], "meta": {"last_page": N}}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('roofz', 'REPLACE_ME', 'GET',
--   '{"agency": "Roofz", "website": "https://roofz.eu"}', '{}', '{}', false);

-- Entree: response must be JSON with {"d": {"aanbod": [...]}}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('entree', 'REPLACE_ME', 'GET',
--   '{"agency": "Entree", "website": "https://entree.nu"}', '{}', '{}', false);

-- 123Wonen: response must be JSON with {"pointers": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('123wonen', 'REPLACE_ME', 'GET',
--   '{"agency": "123Wonen", "website": "https://www.123wonen.nl"}', '{}', '{}', false);

-- Hoekstra: JSON API (items or data array); URL at /api/pim or /api/search
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('hoekstra', 'REPLACE_ME', 'GET',
--   '{"agency": "Makelaardij Hoekstra", "website": "https://verhuur.makelaardijhoekstra.nl"}', '{}', '{}', false);

-- Woonin: response must be JSON with {"objects": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('woonin', 'REPLACE_ME', 'GET',
--   '{"agency": "Woonin", "website": "https://ik-zoek.woonin.nl"}', '{}', '{}', false);

-- Woonnet Rijnmond: GraphQL query, method=POST
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('woonnet_rijnmond', 'REPLACE_ME', 'POST',
--   '{"agency": "Woonnet Rijnmond", "website": "https://www.woonnetrijnmond.nl"}', '{}', '{}', false);

-- VBT Verhuurmakelaars: response must be JSON with {"houses": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('vbt', 'REPLACE_ME', 'GET',
--   '{"agency": "VBT Verhuurmakelaars", "website": "https://www.vbtmakelaars.nl"}', '{}', '{}', false);

-- KRK: response must be JSON with {"objects": [...]}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('krk', 'REPLACE_ME', 'GET',
--   '{"agency": "KRK", "website": "https://www.krk.nl"}', '{}', '{}', false);

-- NMG Makelaars: HTML with "article.house.huur" cards
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('nmg', 'REPLACE_ME', 'GET',
--   '{"agency": "NMG Makelaars", "website": "https://www.nmgmakelaars.nl"}', '{}', '{}', false);

-- ATTA: HTML with "div.list__object" cards
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('atta', 'REPLACE_ME', 'GET',
--   '{"agency": "ATTA", "website": "https://REPLACE_ME"}', '{}', '{}', false);

-- Woningnet DAK regional portals (social housing, POST to mijndak.nl)
-- Response: {"data": {"PublicatieLijst": {"List": [...]}}}
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('woningnet_almere', 'REPLACE_ME', 'POST',
--   '{"agency": "Woningnet Almere", "website": "https://almere.mijndak.nl"}', '{}', '{}', false);

-- Hexia platform corps (multiple housing corps on the same platform)
-- Response: {"data": [...]} with rentBuy, city.name, street, houseNumber, netRent, urlKey
-- INSERT INTO hermes.targets (agency, queryurl, method, user_info, post_data, headers, enabled)
-- VALUES ('hexia_dewoningzoeker', 'REPLACE_ME', 'GET',
--   '{"agency": "De Woningzoeker", "website": "https://www.dewoningzoeker.nl"}', '{}', '{}', false);
